### ISSUE TITLE
Total Number of Tweets Crawled not as much as Requested

### ISSUE THREAD

**Issue by seuriously** [ajav17/TwitterAnalytics#1]
Hi,

I input number of tweets requested to 18000 (max tweet per 15 minutes) but the dashboard only gives me 1000 tweets across 2 days. Is there any way for me to get that much request? I think twitter also make it possible for us to take historical 1 week of data.

**Comment by ajav17** [comment]
@seuriously, thanks for your question. This seems to be a limitation of the Twitter Search API. I use twitteR package for this analysis, which provides an interface to the Search API (queryable only for about a week's worth of tweets). You may find this thread useful: https://stackoverflow.com/questions/22052811/twitter-searchtwitter-only-returns-a-small-set-of-tweets.
